apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: valuecomparator
  name: valuecomparator
  namespace: valuecomparator
spec:
  replicas: 1
  selector:

    app: valuecomparator
    deploymentconfig: valuecomparator
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
    type: Recreate
  template:
    metadata:
      labels:
        app: valuecomparator
        deploymentconfig: valuecomparator
    spec:
      containers:
        - image: docker-registry.default.svc:5000/valuecomparator/valuecomparator
          imagePullPolicy: Always
          name: valuecomparator
          ports:
            - containerPort: 6090
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - valuecomparator
        from:
          kind: ImageStreamTag
          name: 'valuecomparator:latest'
          namespace: valuecomparator
      type: ImageChange