apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: value-comparator
  name: value-comparator
  namespace: value-comparator
spec:
  replicas: 1
  selector:

    app: value-comparator
    deploymentconfig: value-comparator
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
    type: Recreate
  template:
    metadata:
      labels:
        app: value-comparator
        deploymentconfig: value-comparator
    spec:
      containers:
        - image: docker-registry.default.svc:5000/value-comparator/value-comparator
          imagePullPolicy: Always
          name: value-comparator
          ports:
            - containerPort: 6090
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - value-comparator
        from:
          kind: ImageStreamTag
          name: 'value-comparator:latest'
          namespace: value-comparator
      type: ImageChange