apiVersion: v1
kind: Service
metadata:
  labels:
    app: valuecomparator
  name: valuecomparator
  namespace: valuecomparator
spec:
  ports:
    - name: 6091-tcp
      port: 6091
      protocol: TCP
      targetPort: 6091
  selector:
    deploymentconfig: valuecomparator
  type: ClusterIP