apiVersion: v1
kind: Service
metadata:
  labels:
    app: value-comparator
  name: value-comparator
  namespace: value-comparator
spec:
  ports:
    - name: 6091-tcp
      port: 6091
      protocol: TCP
      targetPort: 6091
  selector:
    deploymentconfig: logservice
  type: ClusterIP